# Generated by Django 4.2 on 2024-11-15 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='updated_at',
            new_name='updated',
        ),
    ]
