# Generated by Django 4.2 on 2024-11-15 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_rename_updated_at_task_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created_at',
            new_name='created',
        ),
    ]
